import scrapy

class CrawlerItem(scrapy.Item):
    # define the fields for your item here like:
    scrape_date = scrapy.Field()
    category = scrapy.Field()
    sub_category = scrapy.Field()
    brand = scrapy.Field()
    sku_id = scrapy.Field()
    product_name = scrapy.Field()
    price = scrapy.Field()
    mrp = scrapy.Field()
    high_street_price = scrapy.Field()
    out_of_stock = scrapy.Field()
    discount = scrapy.Field()
    size = scrapy.Field()
    qty_left = scrapy.Field()
    product_description = scrapy.Field()
    info_table = scrapy.Field()
    product_url = scrapy.Field()
    image_url = scrapy.Field()


class FactiveItem(scrapy.Item):
    website_id = scrapy.Field()
    scrape_date = scrapy.Field()
    category = scrapy.Field()
    sub_category = scrapy.Field()
    brand = scrapy.Field()
    sku_id = scrapy.Field()
    product_name = scrapy.Field()
    price = scrapy.Field()
    mrp = scrapy.Field()
    high_street_price = scrapy.Field()
    out_of_stock = scrapy.Field()
    discount = scrapy.Field()
    size = scrapy.Field()
    qty_left = scrapy.Field()
    product_description = scrapy.Field()
    info_table = scrapy.Field()
    product_url = scrapy.Field()
    image_url = scrapy.Field()
    usd_price = scrapy.Field()
    usd_mrp = scrapy.Field()
    miscellaneous = scrapy.Field()
